### ISSUE TITLE
Module review: missing documentation

### ISSUE THREAD

**Issue by hilton** [lyubo/play-ebean#1]
We are introducing Play framework module review, to improve the quality of published modules, and have identified an issue with this module.

The module does not have any documentation. Please add documentation in the file documentation/manual/home.textile in Textile format. If you are unable to add documentation, we suggest you ask for help on the play-framework Google Group.

For a template, see https://github.com/playframework/play/blob/master/resources/module-skel/documentation/manual/home.textile

**Comment by lyubo** [comment]
I'll write one. But since ebean will be included by default in 2.0 no as a module I don't see this module very useful in the future.

**Comment by hilton** [comment]
Okay, that's great. Don't forget that it's going to be a while before 2.0 is final, which means that this module is especially useful for people starting now with Play 1.x who want to start with Ebean to make migration to Play 2.0 later easier.

**Comment by lyubo** [comment]
I added documentation page according to the template. Also there is a new version of module uploaded in module repository.

**Comment by hilton** [comment]
That's great, thanks. Note that in your documentation you could also mention the sample apps, which are very useful to someone getting started.
